services:
  web:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mysql
    restart: on-failure
    volumes:
      - .:/app
  mysql:
    image: mysql:9.0
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql     
volumes:
  mysqldata: